name: Build Artifact

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v2
        with:
          repository: valitydev/action-jdk-build
          ref: v1.0.18
          path: .github/actions/action-jdk-build

      - name: Run Build Java
        uses: valitydev/action-jdk-build@v0.0.7